### ISSUE TITLE
Implement connections (friendship) between two users

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#142]
User A says he is connected to B: A->B
This also means that B->A
No confirmation is needed.

**Comment by raphaelfellmer** [comment]
we should not create a connection if it is not from both parties. So as
long B does not accept the connection from A, there is no connection
established

because if i see connection of a user or if I am seeing my own connection,
i only want to see the ones which I  connected and not a one-way wish to be
connected

so: confirmation is need


2016-01-08 13:48 GMT+01:00 Tilmann Becker <notifications@github.com>:

**Comment by tiltec** [comment]
https://trello.com/c/U2Xn5Hib/74-u-3-as-a-user-i-want-to-make-a-request-to-connect-to-another-user-so-that-i-have-an-overview-to-whom-i-am-connected
