### ISSUE TITLE
Address/Location fields

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#168]
In the last meeting, @D0nPiano requested addresses for stores.
Is a simple `address` text field enough? Or should we also store the location with latitude/longitude?
Furthermore, also groups and users could have a location.

**Comment by D0nPiano** [comment]
Personally, I'd love to see the things on a map as soon as possible. So, if coordinates don't mean much more work for you, I'd go with this approach. Especially for stores and groups - I don't really think they are necessary for users though, I'd rather just have a text field there (since I don't think they'd select their actual coord anyways. ...but maybe that's just me :D).
