### ISSUE TITLE
Add images to chat

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-core#32]
Enable users to send images in real time chat
user story #3

**Comment by c-w** [comment]
Does backend actually have to do anything here? The issue seems like a frontend task to me:
- in the UI we have a photo upload button that uploads the image to some resource server
- the UI then creates a new message with `{'type': 'image', 'content': 's3://path/to/image.png'}` which we store in the database
- when the UI renders a thread of messages, it decides how to render the content depending on Message.type

**Comment by tiltec** [comment]
linked to #55

**Comment by NerdyProjects** [comment]
So I don't think we use some kind of resource server, this task is basically about the upload capability with nice-to-have features like a progress bar :)
