### ISSUE TITLE
As a user, I want to be able to set two-weekly pickup dates in a company

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#69]
We might have more than just weekly reoccuring fetch dates.
e.g. I just got a request for a pickup every two weeks.

**Comment by c-w** [comment]
We can solve this (and other recurring responsibilities) in the UI.

In the view to create a new responsibility, we have a calendar when the responsibilities should happen. We can have multi-select on this calendar or some "recurring" button with a schedule. In the backend, we then simply create lots of responsibilities for each instance of the recurrence.

So if a store-owner wants a fortnightly pickup on Wednesdays at 5pm, we'd simply create responsibilities for every other Wednesday at 5pm for the next N months into the future.

The nice thing about this is approach is that users can then sign up for the individual pickups (because they're all independent) without any more work in the backend. The drawback is that we need to set the value of N, but maybe this can also be an option in the UI (like Outlook asking how long the recurrence of some event should last: some number of times or until some date, etc).

Given above explanation, I think this is a front-end task and we can close this backend issue.
