### ISSUE TITLE
Add Django Rest Framework

### ISSUE THREAD

**Issue by NerdyProjects** [yunity/yunity-core#79]

**Comment by c-w** [comment]
Summarizing conversation with @NerdyProjects. Does the framework really buy us anything? It seems as though we'd have to use some hacks to get the API we want via this framework so why not use Django routes directly. The nice thing about the framework is the auto-generated documentation (which we can also get via doc-strings) and the api explorer (which we can code in a day at most).

**Comment by maackle** [comment]
I haven't yet seen what kind of API we want. I think if our API is rather boring and follows closely in step with the schema, it can remove a lot of boilerplate. The main benefit I see is that it encourages consistency -- in URI paths, and in the shape of response data, including serialization of models -- which could be useful for new contributors. I guess there are tools to help with authorization and stuff too. But I'm not familiar enough with it to really endorse it. I would suggest we use it until it's clearly slowing us down, and then switch to normal routes.

**Comment by c-w** [comment]
Yesterday @NerdyProjects told me that the REST framework doesn't natively support operations on resources like the following:

- `POST /chat/{conversationId}/messages` to add a message to a chat
- `POST /chat/{conversationId}/participants` to add a user to the chat
- `DELETE /chat/{conversationId}/participants/{userId}` to remove a user from the chat

So if we want to stick to our API draft, we'd need to implement a work-around that combines Django routes with the REST framework's views... but at that point we introduce a hack, loose consistency and are working against the framework instead of with it -- so why bother and not just use routes directly.

In your reply you mention model serialization, but shouldn't we keep the API unaware of our model? So what does model serialization buy us when we want to use the API to hide the details of our database anyways?

**Comment by c-w** [comment]
As an alternative to the REST framework, we could simply use routing decorators like [django-quicky](https://github.com/sametmax/django-quicky).

According to @NerdyProjects, the only thing we'd lose is the nice auto-generated documentation via Swagger. However, implementing the documentation generation is trivial: have a view on `GET /api` that reflectively finds all the methods with the routing decorator, pulls out the doc-strings and adds some forms to the page to send test responses and render the replies. I estimate this will take 1-2 dev-days of effort.

**Comment by c-w** [comment]
@tiltec: API implementation using django-quicky-esque pseudo-code

File: api/chat.py
```python
@url.post('/api/chat')
def create_chat(request):
  pass

@url.get('/api/chat/{chatId}/messages')
def list_chat_messages(request, chat_id):
  pass

@url.post('/api/chat/{chatId}/messages')
def add_message_to_chat(request, chat_id):
  pass

@url.delete('/api/chat/{chatId}/participants/{userId}')
def delete_user_from_chat(request, chat_id, user_id):
  pass

@url.post('/api/chat/{chatId}/participants')
def add_user_to_chat(request, chat_id):
  pass

@url.get('/api/chat/{chatId}/participants')
def list_users_in_chat(request, chat_id):
  pass
```

File: api/auth.py
```python
@url.post('/auth/login')
def login(request):
  pass

@url.post('/auth/logout')
def logout(request):
  pass
```

Etc.

**Comment by tiltec** [comment]
Nested endpoints are possible with the REST framework with separate routes and ViewSets
POST /chat/{conversationId}/messages to add a message to a chat
POST /chat/{conversationId}/participants to add a user to the chat
DELETE /chat/{conversationId}/participants/{userId} to remove a user from the chat

router.register(r"chat", ChatViewSet)
router.register(r"chat/(?P<conversationId>\d+)/participants", ChatParticipantsViewSet)

**Comment by NerdyProjects** [comment]
The last proposal from c-w looks good.
We have multiple similar endpoints (e.g. post messages to wall/chat) which may use just a little different request-handling code but call the same underlying functionality.
This maps nicely to his suggestion.

**Comment by c-w** [comment]
We decided to go with plain Django routes. See ec886c0
